### ISSUE TITLE
Failing to build package

### ISSUE THREAD

**Issue by satkatai** [fairandsmart/facogen#11]
Hi,

Thank you for open sourcing the project. I am trying to get it up running. Currently I am facing issue in the build stage. Can you please help?

Java version:
```
java 18.0.2 2022-07-19
Java(TM) SE Runtime Environment (build 18.0.2+9-61)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.2+9-61, mixed mode, sharing)
```
Maven version:
```
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T19:06:16+04:00)
Maven home: /Users/sat/Documents/apache-maven-3.6.2
Java version: 18.0.2, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-18.0.2.jdk/Contents/Home
Default locale: en, platform encoding: UTF-8
OS name: "mac os x", version: "11.6.7", arch: "x86_64", family: "mac"
```

Command i am executing:
```
mvn quarkus:dev
```
Stack Trace:
![st](https://user-images.githubusercontent.com/44122848/183407542-a23c99a7-df54-4e17-ad22-fb47e2274d82.png)

```
java.lang.IllegalArgumentException: Unsupported class file major version 62
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:196)
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:177)
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:163)
	at net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:86)
	at net.bytebuddy.pool.TypePool$Default.parse(TypePool.java:679)
	at net.bytebuddy.pool.TypePool$Default.doDescribe(TypePool.java:665)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution.access$001(TypePool.java:745)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution.doResolve(TypePool.java:843)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:912)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getTypeVariables(TypeDescription.java:8324)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isGenerified(TypeDescription.java:7978)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Reifying.onNonGenericType(TypeDescription.java:1655)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Reifying$1.onNonGenericType(TypeDescription.java:1611)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfNonGenericType.accept(TypeDescription.java:3752)
	at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection.accept(TypeDescription.java:6270)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyzeNullable(MethodGraph.java:615)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:629)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyze(MethodGraph.java:596)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyzeNullable(MethodGraph.java:615)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:629)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.compile(MethodGraph.java:567)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$AbstractBase.compile(MethodGraph.java:465)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.ByteBuddyEnhancementContext.lambda$resolveGetter$0(ByteBuddyEnhancementContext.java:91)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.ByteBuddyEnhancementContext.resolveGetter(ByteBuddyEnhancementContext.java:90)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl$AnnotatedFieldDescription.getGetter(EnhancerImpl.java:501)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl$AnnotatedFieldDescription.doGetAnnotations(EnhancerImpl.java:530)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl$AnnotatedFieldDescription.getAnnotations(EnhancerImpl.java:509)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl$AnnotatedFieldDescription.hasAnnotation(EnhancerImpl.java:459)
	at org.hibernate.bytecode.enhance.spi.DefaultEnhancementContext.isPersistentField(DefaultEnhancementContext.java:101)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.ByteBuddyEnhancementContext.isPersistentField(ByteBuddyEnhancementContext.java:69)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.PersistentAttributeTransformer.collectPersistentFields(PersistentAttributeTransformer.java:82)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.createTransformer(EnhancerImpl.java:340)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.doEnhance(EnhancerImpl.java:327)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.lambda$enhance$0(EnhancerImpl.java:132)
	at org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState.rewrite(ByteBuddyState.java:141)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.enhance(EnhancerImpl.java:132)
	at io.quarkus.hibernate.orm.deployment.HibernateEntityEnhancer.enhance(HibernateEntityEnhancer.java:96)
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.enhanceEntities(HibernateOrmProcessor.java:828)
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.enhancerDomainObjects(HibernateOrmProcessor.java:528)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)

Resulted in: org.hibernate.bytecode.enhance.spi.EnhancementException: Failed to enhance class io.quarkus.hibernate.orm.panache.PanacheEntity
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.enhance(EnhancerImpl.java:138)
	... 13 more
```

**Comment by SamSamhuns** [comment]
Try to use `JDK 11/12` and `maven 3.8.6`, or play around with different versions of JDK and maven

**Comment by satkatai** [comment]
Thank you for saving my life.

**Comment by SamSamhuns** [comment]
You are welcome
